[base]
policy_name = "CleanRLPolicy"
# rnn_name = "Recurrent"  # Assign a value when needed.

[env]
reward_scaling = 0.1

[policy]

[rnn]

# Refer https://colab.research.google.com/github/google/brax/blob/main/notebooks/training_torch.ipynb
[train]
seed = 1
torch_deterministic = true
cpu_offload = false
device = "cuda"
learning_rate = 3e-4
lr_decay_rate = 1e-3
gamma = 0.97
gae_lambda = 0.95
update_epochs = 4
norm_adv = true
clip_coef = 0.2
clip_vloss = true
vf_coef = 0.5
vf_clip_coef = 0.2
max_grad_norm = 0.5
ent_coef = 0.01
# target_kl = None  # Assign a value when needed.

num_envs = 1024
# NOTE: gpu-based envs do not use these
# num_workers = 1
# env_batch_size = 1
# zero_copy = false
data_dir = "experiments"
checkpoint_interval = 1000
batch_size = 65536
minibatch_size = 8192
bptt_horizon = 8

compile = true
compile_mode = "reduce-overhead"

total_timesteps = 3_000_000
eval_timesteps = 1_100_000


### Sweep related parameters

num_sweeps = 500

[sweep]
method = "bayes"
name = "sweep"

[sweep.metric]
goal = "maximize"
name = "environment/episode_return"

[sweep.parameters.train.parameters]

# NOTE: These are differently handled by CARBS
# If the sampled params are out of range, the wandb sweep crashes
total_timesteps = { min = 1_000_000, max = 300_000_000 }
batch_size = { min = 1, max = 2_000_000 }
num_minibatches = { min = 1, max = 10000 }
# minibatch_size = { min = 1, max = 2_000_000 }
bptt_horizon = { min = 1, max = 32 }
num_envs = { min = 256, max = 8192 }

# These' scales are good for CARBS
learning_rate = { min = 1e-5, max = 1e-1 }
lr_decay_rate = { min = 1e-5, max = 5e-2 }
gamma = { min = 0.0, max = 1.0 }
gae_lambda = { min = 0.0, max = 1.0 }
update_epochs = { min = 1, max = 20 }
clip_coef = { min = 0.0, max = 1.0 }
vf_coef = { min = 0.0, max = 10.0 }
vf_clip_coef = { min = 0.0, max = 1.0 }
ent_coef = { min = 1e-4, max = 0.05 }
# max_grad_norm = { min = 0.0, max = 10.0 }

[carbs]
# Special cases, the scale of which are different from above
# NOTE: The actual values of batch_size, num_minibatches, bptt_horizon are 2**suggested
# These parameters need to be processed before used in training
total_timesteps = { min = 10_000_000, max = 200_000_000, space = "log", search_center = 20_000_000, is_integer = true }
batch_size = { min = 14, max = 20, space = "linear", search_center = 17 }
num_minibatches = { min = 1, max = 10, space = "linear", search_center = 3 }
# minibatch_size = { min = 1, max = 10, space = "linear", search_center = 4 }
bptt_horizon = { min = 1, max = 5, space = "linear", search_center = 3 }

# TODO: make num_envs sweep work. It does not work now.
# Use 2^suggested, thus 1024, 2048, 4096, 8192
num_envs = { min = 8, max = 14, space = "linear", search_center = 11 }

# Others: append min/max from wandb param to carbs param
learning_rate = { space = "log", search_center = 2e-3 }
lr_decay_rate = { space = "log", search_center = 5e-3 }
gamma = { space = "logit", search_center = 0.97 }
gae_lambda = { space = "logit", search_center = 0.90 }
update_epochs = { space = "log", search_center = 5 }
clip_coef = { space = "logit", search_center = 0.5 }
vf_coef = { space = "linear", search_center = 1.0 }
vf_clip_coef = { space = "logit", search_center = 0.5 }
ent_coef = { space = "log", search_center = 0.002 }
